# Updated dockerfile to fix vulnerabilities
FROM docker.io/nginx:1.24

# Update and install the specific package
RUN apt-get update && \
    apt-get install -y libnghttp2-14 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*